### ISSUE TITLE
Problem whit Tensorflow module

### ISSUE THREAD

**Issue by nikyred78** [mjdargen/RPi-La-Croix-Flavor-Detector#1]
Hello,
Thanks for you job , this is a good idea.

After I following the procdure , when I start the file python , return an error for the module Tensorflow missing.
I have following the procedure correcty , but is not start for this error.
What I can solve this?
Thanks

**Comment by mjdargen** [comment]
I have updated the installation script to retrieve a newer version of Tensorflow (2.4.0). This should help solve some of the issues that you may be running into. However, please remember that it is installing these Python packages in a virtual environment! You must activate the virtual environment first to be able to use these packages. By default, the virtual environment name is TMenv.
